import "./globals.css";
import Header from "../components/Header";

export const metadata = {
  title: "Unbound",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="antialiased overflow-hidden">
        <Header />
        {children}
      </body>
    </html>
  );
}


